apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana
resources:
  - ../../generated/grafana
  - ./sealedsecret.gf-admin.yaml
  - ./sealedsecret.gf-azuread.yaml
  - ./httproute.yaml
