apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kiali
resources:
  - ./namespace.yaml
  - ../../generated/kiali
  - ./sealedsecret.oauth2-proxy.yaml
  - ./sealedsecret.oauth2-proxy-redis.yaml
  - ./httproute.yaml

patchesJson6902:
  - target:
      version: v1
      kind: Service
      name: kiali
    patch: |
      - op: replace
        path: "/spec/ports/0"
        value:
          appProtocol: tcp
          name: http
          port: 80
          protocol: TCP
