apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    name: istio-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-ingress
  labels:
    name: istio-ingress
    istio-injection: enabled
