apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
  - ./namespace.yaml
  - ../../generated/argo-cd
  - ./sealedsecret.yaml
  - ./httproute.yaml

patchesStrategicMerge:
  - ./overlays/configmap.yaml
  - ./overlays/networkpolicy.yaml
  - ./overlays/secoverride.yaml
