apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
  - ./namespace.yaml
  - ../../bases/argo-cd
  - ./httproute.yaml

patchesStrategicMerge:
  - ./overlays/configmap.yaml
