apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCmN9jBMcd6Wp3OycJVYZiuXwBerFWKQy68nT3CS2jef0k0489Ql/5qj12vpHO3oRVI577V66XT6R8mVybbn530EC1y4MQO0gi0+V/7BoI3o+W8uAxlkX0t+WOmvn+ts35yjheqOSEyoEOEk7z+EgoHkOyYr55ZXuvmsw7asK6LnbkAAsti/r2c/Etn9Crabppwxrou7f69u3uzxXzOkN/G8aH0Lqehq5vgUz43dUfcT31RpfU4J0IDa2Hf/g5IAeJfps4jIcGrabbirsGg/mSTNVDw39G9cDVXFUQjRvGu5iJcjiqESxeiZZdWpGdxzf+8gP/p8gc5/HeTpmaY9UGe3M/1Nye4v9esdYbIXIAExGJ02U0ENX/YzygD0VX0Sr05Ta7uxHOV9WzqUPAAzamz8rp6qNMI4EtCilp7l62XW6a3ttDp0M4pBU7GlWPUdq1IWn11kfwM0kg5hFomqJ0HmQZh0BcgVwNPAAYtFqO5u03K0S9SXLtIviuRRB4e2siRnPmg1eSkzzh37iv9p4q7ESEkvvr/77bBEEC3VL+AIoduDOfdVeoJ3C557LxyJDspe+ZxHUg1tamtKLGiwV1jPIxpNqTq7+0gYO5pvP9T7871ZoLljmLZgDFROvekXop1HhiSRZOOZwfuJvhTGAjeFb6l+4Vq/Q99jLgrgcGqep1dVQTjWJy+RrXw/j5VUaV/kcUe4cPw+ki4741yvInOxm/1jptaqPiO0MpWFJ7+mEFHhk1fFpuv
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
