apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared
  namespace: cloudflared
spec:
  encryptedData:
    token: AgCbu6/A7WMe4z8NIAJG7bqWvJGWV/SbCaUT0J5cgcDuqIMIqJgVRapc0FlXMv3d41pF93qqxIQohSFPF9YwfY/mBgCz7OE0mviOcNRivfbSZVleElnit8pvIXdO6vzB+rCppO31dv9o13iqhTCOL4b91rPHTY63i8SkrUV2KskzJ9x4BeZ7UWR3WR2u2+kjYrSTJPJfE46ELslvLQbDbfWzI1youagjdfMiMlX42OKfJRynOoNb21UpwtUMePBT42sgUgrZgpXrpFUDh5HU0glFK50Liu6MJFlwEaB2XjFqw0x2lqm5o3cI7esRIBa6OQ3dKl/+QsD17bOIzF4Kr4A0zMF1vA/+gWLJkJGgo1JEWqA8pENzYiBvkHGKktgzj5jOm2GZWZRisvxTEbSW/nG5B1zjYnBdE1adEPRxpMAlsg+7BnLynusiGitgtKiuaEo0IuQDrCBYGQcXcwKWv4r9czy1jixIsxhNG8cNTLWun+aatkppM5Ygzbw8HAcGnGokD7HsqhoICEZ9LriZEw2fZJUpVNH7MYJH0GdX0jKMXkx9XeVDfJE2PkZBDVSMLSq2nK0GHf/cOFAsDExSXUXoyotUpf5uietPP44Dm1ahjt3l2tjhh3A4LvrxA6dzoUH/eQD4pYHzza6YryT7y4nghB9UenKVZY4l68k2B0xZRyYhxJMfvMTbqlXLhZsEMD87E+1Y9Bml/15FdK8FKJj8XXUb7TeWw3Av5X2qfE268Rqx3k+iKKBOtwkr9i171DiCc+2uGbMKEzEb/aL/gOzVL6IiM1LKQXLGq9CoGo3AGMYb2lNm+JEnTTgJhqEl5fPZvX8ypbMm6aVc/miop/9o5oQCs9yf0/ldPGYSNfNltBhTs3LOX+2PgnUUcK+PalHjG71wnXfQSDSw1b4Yp23xPfREguU3rxHIJqp91jY2GC4pWf6+jLdz
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared
      namespace: cloudflared
    type: Opaque
