apiVersion: v1
kind: ConfigMap
metadata:
  name: documentserver
  namespace: onlyoffice
data:
  AMQP_HOST: docs-rabbitmq
  AMQP_PORT: '5672'
  AMQP_PROTO: amqp
  AMQP_TYPE: rabbitmq
  AMQP_USER: user
  AMQP_VHOST: /
  DB_HOST: docs-postgres-postgresql
  DB_NAME: docs
  DB_PORT: '5432'
  DB_TYPE: postgres
  DB_USER: docs
  METRICS_ENABLED: 'false'
  REDIS_SERVER_DB_NUM: '0'
  REDIS_SERVER_HOST: docs-redis-master
  REDIS_SERVER_PORT: '6379'
  REDIS_SERVER_USER: default
  WOPI_ENABLED: 'false'
