apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: onlyoffice
resources:
  - ../../generated/onlyoffice
  - ./sealedsecret.docs.yaml
  - ./sealedsecret.postgres.yaml
  - ./sealedsecret.redis.yaml
  - ./sealedsecret.rabbitmq.yaml
  - ./configmap.yaml
  - ./persistentvolumeclaim.yaml
  - ./deployment.yaml
  - ./service.yaml
  - ./httproute.yaml
