apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: docs-redis-secret
  namespace: onlyoffice
spec:
  encryptedData:
    redis-password: AgAHV4C72ZJOJfrlrNOv098P5KTKCVqW28Bxe7j3fv2QYVj61PfbL9qhRWDyVssM+MnKcjtI4zhKmg2Y7nT1WwFVPFkVKdfTXDbl8jXEpHIdhcg3ffiiC2kyihi++R9Iy5ObROFmgimDabFvTekIE5zsESLSZfZ8c5+BwMsN/pe4D5QCMxHHdBvTeqd2jxYrEMVJ/b1EDKM5LUCAG8wH/rRPbnQFwHA7iUST9GAQ3SNOwxMkEDLUQORxFPXWIZGwiiXKGpaixa6seU1TwPqz8mWQnLsmjFPvyOyykB6xMH2M3DhHCSK6QREWD9Z7LvmwylMcUEEr8GmJzRQkrN/vuUMyOeRSJdGw/Y205eOa7LFtw6cetFh4i5wPC8XlxQuFbv/UEUryZHn1eBMKan8U4OjYSoije7mKh+7aoCVmviZV8R11NRrl4dOW9zTL5pVGEqpuC18xwnld0IwEYIs2kP8kkHgYLQvmrNbDG2NuhCzol9k3TX0KQW2+ZEb8w+fuRJq7isSCK0VjFLK3T58M5NxN++YnQ3oUDEljt8cRygiSuT4B/SJYOrub7w0Va3FiOSDRWK7DSwUSvdfpZqfvqPIh5wG9qwM7asPR8huHFScUwaxv7/r+8NGHFpLO+ERC9dBArf2tL5otKOP1ugGq1sQYxNNYX49Nl5QCW9mR8tEmN0aaTrS8iE/ccF8/b1NejMSpUqLy6RkAvszOqgnDEWsgJ6UnZFIzWtFuJXbZrmflK9KWNcPOCEumnqY7+zgxJhNia6uvrKFFWTAbOOFHu2zu
  template:
    metadata:
      creationTimestamp: null
      name: docs-redis-secret
      namespace: onlyoffice
    type: Opaque
