apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: httpbin
resources:
  - ./namespace.yaml
  - ./serviceaccount.yaml
  - ./service.yaml
  - ./deployment.yaml
  - ./httproute.yaml
