apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./namespace.yaml

helmCharts:
  - releaseName: harbor
    namespace: harbor
    name: harbor
    repo: https://helm.goharbor.io
    version: 1.11.1
    valuesFile: values.harbor.yaml
  - releaseName: harbor-postgres
    namespace: harbor
    name: postgresql
    repo: https://charts.bitnami.com/bitnami
    version: 12.1.14
    valuesFile: values.postgresql.yaml
  - releaseName: harbor-redis
    namespace: harbor
    name: redis
    repo: https://charts.bitnami.com/bitnami
    version: 17.6.0
    valuesFile: values.redis.yaml
