apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./namespace.yaml

helmCharts:
  - releaseName: docs-rabbitmq
    namespace: onlyoffice
    name: rabbitmq
    repo: https://charts.bitnami.com/bitnami
    version: 11.6.1
    valuesFile: values.rabbitmq.yaml
  - releaseName: docs-redis
    namespace: onlyoffice
    name: redis
    repo: https://charts.bitnami.com/bitnami
    version: 17.6.0
    valuesFile: values.redis.yaml
  - releaseName: docs-postgres
    namespace: onlyoffice
    name: postgresql
    repo: https://charts.bitnami.com/bitnami
    version: 12.1.12
    valuesFile: values.postgresql.yaml
