apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/kubernetes-sigs/gateway-api/config/crd/experimental?ref=v0.6.0

helmCharts:
  - releaseName: prometheus-operator-crds
    name: prometheus-operator-crds
    repo: https://prometheus-community.github.io/helm-charts
    version: 1.1.0
    includeCRDs: true
