apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../generated/istio
  - ./certificate.yaml
  - ./gateway.yaml
  - ./peerauthentication.yaml

patchesJson6902:
  - target:
      version: v1
      kind: ValidatingWebhookConfiguration
      name: istiod-default-validator
      group: admissionregistration.k8s.io
    patch: |-
      - op: replace
        path: "/webhooks/0/failurePolicy"
        value: Fail
