apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../bases/istio
  - ./certificate.yaml
  - ./gateway.yaml
  - ./peerauthentication.yaml

patchesJson6902:
  - target:
      version: v1
      kind: ValidatingWebhookConfiguration
      name: istiod-default-validator
      group: admissionregistration.k8s.io
    patch: |-
      - op: replace
        path: "/webhooks/0/failurePolicy"
        value: Fail
  - target: # Remove when generated build.yaml has correct apiVersion
      version: v1beta1
      kind: PodDisruptionBudget
      name: '.*'
      group: policy
    patch: |-
      - op: replace
        path: "/apiVersion"
        value: policy/v1
  - target: # Remove when generated build.yaml has correct apiVersion
      version: v2beta2
      kind: HorizontalPodAutoscaler
      name: '.*'
      group: autoscaling
    patch: |-
      - op: replace
        path: "/apiVersion"
        value: autoscaling/v2
