apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./namespace.yaml

helmCharts:
  - releaseName: kiali-server
    namespace: kiali
    name: kiali-server
    repo: https://kiali.org/helm-charts
    version: 1.63.1
    valuesFile: values.yaml
