apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./namespace.yaml

helmCharts:
  - releaseName: bookstack-mariadb
    namespace: bookstack
    name: mariadb
    repo: https://charts.bitnami.com/bitnami
    version: 11.4.5
    valuesFile: values.mariadb.yaml
