apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bookstack
resources:
  - ../../generated/bookstack # MariaDB, Redis
  - ./sealedsecret.bookstack.yaml
  - ./sealedsecret.mariadb.yaml
  - ./sealedsecret.redis.yaml
  - ./configmap.yaml
  - ./persistentvolumeclaim.yaml
  - ./deployment.yaml
  - ./service.yaml
  - ./httproute.yaml
