apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookstack-files
  namespace: bookstack
spec:
  storageClassName: csi-cephfs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 16Gi
