apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: bookstack-redis-secret
  namespace: bookstack
spec:
  encryptedData:
    redis-password: AgBYzJ667s3Ja8wKi5YEyGrXlRs+elReJYesrV2cxc9Mm06rE3TEd9jnIb58Au7EqjukORl5YVy+08MCJm0AA9JhOawTGY9qgdOkHP368wY6ZIQ2BnvpwFMUlh6vLwzHJK2i1tXmIVcontiQ7UYoqMquqnOgEapagt7JWERlNZrvx6ZDUUP9C9aVW8+JzvKolw2p9bVmJ/XO5Zah5J8a6i+1btFQWEqmG00CiDx4CI81LP7PTUV7Hu0uSgeYp8eW0yObQ5okkSd8WgKn/351aFT6AN2QDXGbmAfN77ivkRMFIrBpz44SkTQ+KosdxvH2e0uPDT7bwJJA93E4V7/A+LiiWyk0xl7aPkGAk+EnKS3TZK8+Eu0C44O7H7LaBQlmq28x5f2zd0g30M0YejLTmso8hScH+3YamdYqeAHdVZCk3twJJ9ELF2ATdnUBNs6FXHGndKojkSgOczMTvcaU1LZAK6B//W0qHvCwX3qdBHx/lnj6J8jOMIE0cVX+ImIP/Q/jrnJVG1BAuWs29/qGHf5vVK993JzfsMwMjmfNmNj9vf8MYDQ5iouUER2Bd7Ic2MyFnTaNNRT5PCcs+daFwn915IHDSkjJ77aiJ8K76DJ4Ng43cnM0tDOoQXRlpfTZhBqGXjg7BbFIKe/B9RB8K4aII8284L8sw7bJgjWDxI9SaqJ038AsabmQ8ZHOQS2dSUWbZpk6haNQZm9CU3WuZjjMLLC3Ih76paS7ugnoWQnrOJDwgtLhN+Bf8XBp1RijhZr3XtTvVekm++2HMJn6/dS5
  template:
    metadata:
      creationTimestamp: null
      name: bookstack-redis-secret
      namespace: bookstack
    type: Opaque
