apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: harbor
  namespace: harbor
  releaseName: harbor
  repo: https://helm.goharbor.io
  version: 1.11.0
  valuesFile: values.yaml
