apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./namespace.yaml

helmCharts:
  - releaseName: ceph-csi-rbd
    namespace: ceph-csi-rbd
    name: ceph-csi-rbd
    repo: https://ceph.github.io/csi-charts
    version: 3.7.2
    valuesFile: values.ceph-csi-rbd.yaml
    includeCRDs: true
