apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana
resources:
  - ./namespace.yaml
  - https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/main/manifests/grafana-dashboardSources.yaml
  - https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/main/manifests/grafana-dashboardDefinitions.yaml

helmCharts:
  - releaseName: grafana
    namespace: grafana
    name: grafana
    repo: https://grafana.github.io/helm-charts
    version: 6.50.7
    valuesFile: values.yaml
