apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./namespace.yaml

helmCharts:
  - releaseName: grafana
    namespace: grafana
    name: grafana
    repo: https://grafana.github.io/helm-charts
    version: 6.50.7
    valuesFile: values.yaml
