apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nextcloud
resources:
  - ../../bases/nextcloud
  - ./sealedsecret.postgres.yaml
  - ./sealedsecret.redis.yaml
  - ./sealedsecret.nextcloud.yaml
  - ./sealedsecret.config.yaml
  - ./httproute.yaml

patchesStrategicMerge:
  - ./overlays/deployment.yaml
