apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud-secret
  namespace: nextcloud
spec:
  encryptedData:
    nextcloud-password: AgCjspErTqHhHbIRjuMQs0qGJ6DG+BbbX/0nLR52H9h2rR9FoU6/RkTmQQU8jkc8nyoxLK5P+LtAXk3kd0CeiICbBBwg9w8sOLYjGR+S4i3JQV3NsyYdtiRjYqjsCupV3lIqYW0yMbSZxGRBJY+1Y2c0rQJZK0xZeim0VmMq0B5lip3HWx/v6BbsY74FljV5ikoC6SsnsjZKxYJYJ4Un7HEPZecqZDxIJZR4scYX9qJnYy+1upAlsnHGH5Oml+TmMlYOAUHbpmBWxlilB7DgvYoG+4WBuMTNX9nO0RvBJhsGopl2zkxuqe4vHLX6xOUK3HLhPVDAoTaYBvP9dWXJWcI+TosZ0umLnkiztM+mgvHWak7Pulqk8AMTmtjBQGINfRf4xebztuAXCEZqocOOqgKXpdBsE7jYs34PxOx7ObRW8hBSgx0l8kL4Jb6UX7uZ7SeB9JRiqHzdLsBECAxvW8wfD5CG0Zb0QDlJeO6uFBKDS9oQhq88VDfOkMQRwvG2kQocIjB373+NL1zesZMViMlwkIZT3mH+AYyESavMeiKpEnnqwb0nToBXXpsZzHD6xIPrEMFgPc/9K7bBtavinVktr1F+3zNo7pe4wKray6x8UmOplT0w/RZM82oW6reAmBmN45QRTQgj3cmfTVgexygsJyhLtEA3Vsoj7aD1IAQsgoef+DRWBwOujozbtopk1ttxPe6FgSAgWX3bLSCRMzx9CBVJ0VmoJ1AVT+Hh9st+j6TCDq3vzH4yXwVnS74RJZA4IdbpIuMDduwiaUubH+xE
    nextcloud-username: AgBG2HI97LJqY+Z2dw12es0GSwp4OxPrgHb/N+HaxjNG5/mJ8coAX0fbFak/ILwyz+rN3886GIrZgffKPav4Jc8a6xbDLUkh/8rAUi96C0LSdk6/iL8dhQFolyYZDljJK2FziUOwM5FkuEbWUa7+U5kVLAJgi6NQ4Gv26El4+BpGl4XrgxomF36IPXQyKEnK8dXoe/B60dktz/IIm92HqkEQn54PlMjpZXHducYmpiG8BFbOaaOhkk/Dr1MmAR+Ck1kgk3TuHMkc48WiJZ8VVbf0LVag5PGjhdh+iHKMW/opgQYZ09xKeJnErLfxy7osyQR0yT6f+sBFkPEsuPhh5iJTxrRHcxjEpTX1BYWoqziAHa4O0nDL9z2lAuhPVh6vfMOktUbgTEFGybk6dMDHxnPfGYZPhrk0tjdAHlTyvbwMTyYN+wiKgS4cDkkHvnvIdxWcY4WknHnglVO4r5zIZKlQ4jDC/yjpO6TivAGHbzIotnmXunijCAyGKh7OaAZ6q7VKGD946ojVK8ErZLqUA8FMq/+iXvtjHsU+MCewGKqMH50vmCTH9E1LuP+K12n4yqYZvJM0CfdgO8yTHnJ9omWGq3cdciKp7Pqg1maeHWUe0oEYArK2gtNh/JVyCTZAaGYYU1coNyH3otxfoPs2Vv/xPTN+Y3Os9qtsL/FZFFna7YoYlBWZNVbx23kL/lffU+HVscjLoA==
  template:
    metadata:
      creationTimestamp: null
      name: nextcloud-secret
      namespace: nextcloud
    type: Opaque
